version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/presentations

    branches:
      only:
      - master

    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "requirements.txt" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-

      - run:
          name: Install Python and AWS-CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y python-pip python-dev
            sudo pip install awscli

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

#      - save_cache:
#          paths:
#            - ./venv
#          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: collect all presentations
          command: ./build.py presentations.json

      - run:
          name: Sync to S3 bucket
          command: aws s3 sync _site/ s3://innovation-lab.cz/presentations/ --delete --region eu-central-1

